name: Android CD - Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history and tags

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        echo $KEYSTORE_BASE64 | base64 -d > app/keystore.jks

    - name: Extract release notes
      id: release_notes
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

        # Debug: Show all tags
        echo "🔍 All tags in repository:"
        git tag --list 'v*'

        # Calculate version code from tag (e.g., v1.0.0 -> 1, v1.1.0 -> 2, etc.)
        # Count all tags to get incrementing version code
        TAG_COUNT=$(git tag --list 'v*' | wc -l)
        echo "VERSION_CODE=$TAG_COUNT" >> $GITHUB_OUTPUT

        # Extract version name from tag (remove 'v' prefix)
        VERSION_NAME=${VERSION#v}
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_OUTPUT

        # Debug output
        echo "📦 Version Information:"
        echo "  Tag: $VERSION"
        echo "  Version Code: $TAG_COUNT (counted from git tags)"
        echo "  Version Name: $VERSION_NAME"

        # Extract changelog for this version
        if [ -f CHANGELOG.md ]; then
          # Get content between this version and the next
          awk "/## \[$VERSION\]/{flag=1; next} /## \[/{flag=0} flag" CHANGELOG.md > release_notes.txt
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
          cat release_notes.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        else
          echo "RELEASE_NOTES=Release $VERSION" >> $GITHUB_OUTPUT
        fi

    - name: Run tests
      run: ./gradlew testDebugUnitTest

    - name: Build release APK
      run: |
        echo "🔨 Building APK with VERSION_CODE=$VERSION_CODE and VERSION_NAME=$VERSION_NAME"
        ./gradlew clean assembleRelease \
          -PversionCode=$VERSION_CODE \
          -PversionName="$VERSION_NAME" \
          --no-daemon \
          --no-build-cache
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        VERSION_CODE: ${{ steps.release_notes.outputs.VERSION_CODE }}
        VERSION_NAME: ${{ steps.release_notes.outputs.VERSION_NAME }}

    - name: Build release AAB
      run: |
        echo "🔨 Building AAB with VERSION_CODE=$VERSION_CODE and VERSION_NAME=$VERSION_NAME"
        ./gradlew bundleRelease \
          -PversionCode=$VERSION_CODE \
          -PversionName="$VERSION_NAME" \
          --no-daemon \
          --no-build-cache
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        VERSION_CODE: ${{ steps.release_notes.outputs.VERSION_CODE }}
        VERSION_NAME: ${{ steps.release_notes.outputs.VERSION_NAME }}

    - name: Verify AAB version
      run: |
        echo "📦 Verifying AAB was built with correct version..."
        echo "Expected VERSION_CODE: ${{ steps.release_notes.outputs.VERSION_CODE }}"
        echo "Expected VERSION_NAME: ${{ steps.release_notes.outputs.VERSION_NAME }}"

        # Extract AndroidManifest.xml from AAB and check version
        unzip -p app/build/outputs/bundle/release/app-release.aab base/manifest/AndroidManifest.xml > manifest.xml || true
        if [ -f manifest.xml ]; then
          echo "✅ AAB file exists and is valid"
          ls -lh app/build/outputs/bundle/release/app-release.aab
        else
          echo "⚠️ Could not extract manifest"
        fi

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ steps.release_notes.outputs.VERSION }}
        body: ${{ steps.release_notes.outputs.RELEASE_NOTES }}
        files: |
          app/build/outputs/apk/release/app-release.apk
          app/build/outputs/bundle/release/app-release.aab
        draft: false
        prerelease: false
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: me.tewodros.vibecalendaralarm
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: internal  # Options: internal, alpha, beta, production
        status: completed
        whatsNewDirectory: distribution/whatsnew
        mappingFile: app/build/outputs/mapping/release/mapping.txt

    - name: Clean up keystore
      if: always()
      run: rm -f app/keystore.jks
